name: CI-prod

on:
  push:
    branches:
      - prod

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and test with Maven
        run: mvn clean verify

      - name: Check code coverage
        run: |
          coverage=$(awk -F',' '/<counter type="LINE"/ { print $5 }' target/site/jacoco/jacoco.csv | sed 's/%//')
          if (( $(echo "$coverage < 60" | bc -l) )); then
            echo "Code coverage is less than 40%"
            exit 1
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: maxtro2002/devops_entraga1:latest
          secrets: |
            DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}
